COURT_HEIGHT = 800
COURT_WIDTH = 1200
PADDLE_HEIGHT = 90
PADDLE_WIDTH = 15
BALL_RADIUS = 12
INITIAL_BALL_SPEED = 10
PADDLE_GAP = 10
PADDLE_SPEED_DIVISOR = 15
PADDLE_CONTACT_SPEED_BOOST_DIVISOR = 4
SPEED_INCREMENT = 0.6
SERVING_HEIGHT_MULTIPLIER = 2
PLAYER_COLOURS = {1: 'yellow', 2: 'grey'}
MAX_COMPUTER_PADDLE_SPEED = 30
MIN_COMPUTER_SERVE_DELAY = 5
MAX_COMPUTER_SERVE_DELAY = 10


